### ISSUE TITLE
My thoughts

### ISSUE THREAD

**Issue by ghost** [ayaka14732/ayaka-site#1]
很高兴认识你。
第一次看到你的博客就被吸引了。
然后魔改，却变成四不像的样子，ahoy~
我也喜欢了pandoc，强迫我学会DIY。
我根据文档加入了default.html进行更精细的调控。
比如文章末尾的时间，可以用$if(date)$(跳过了pandoc.yaml)直接生成
还有自动生成文章列表，我用shell实现的，不知道你的怎么做到的。
还有你的博客真的很漂亮，样式简约，元素很少，看起来很舒服，很钦佩你。也给我提供了好思路！
我的[博客](https://7ity.github.io)也在翻修中，我觉得不是很好，但我喜欢构建它的过程！

**Comment by ayaka14732** [comment]
谢谢！你修改的部分很有创意，我也会借鉴你的做法～

**Comment by ghost** [comment]
> 谢谢！你修改的部分很有创意，我也会借鉴你的做法～

Yesterday I added a feature that about light mode, although before always dark style. Now now color looks a bit odd. It need to repair, next vacation I guess. Hack ¶∆¶

**Comment by ghost** [comment]
It will changed depended on time and system-setting.
And I recovered former style.

**Comment by ayaka14732** [comment]
自动生成文章列表我没有做，是手工修改的，因为我觉得手工修改也不是很麻烦 XD

**Comment by ayaka14732** [comment]
Now I am considering dark mode, but bright pictures seem to be a difficulty.

**Comment by ghost** [comment]
> Now I am considering dark mode, but bright pictures seem to be a difficulty.

You can employ `filter: brightness(70%)` to decline brightness
