### ISSUE TITLE
[Typo] cppregex: import -> #include

### ISSUE THREAD

**Issue by Cycatz** [ayaka14732/ayaka-site#2]
In the article [cppregex](https://ayaka.shn.hk/cppregex/), all `#include` lines in the example code were written as `import`.

**Comment by ayaka14732** [comment]
`import` is also correct

**Comment by ayaka14732** [comment]
As this is a feature, not a bug, I am going to close this issue for now.

**Comment by Cycatz** [comment]
Oh cool! I really don't know this feature!
